---
title: "Homework 6"
---

###Description of the dataset

We choose the dataset of NY National Oceanic and Atmospheric Association (NYNOAA). It includes 7 varibles: id (Weather station ID), date (Date of observation), prcp(Precipitation), snow (Snowfall), snwd (Snow depth), tmax (Maximum temperature) and tmin (Minimum temperature). 

We mainly focus on the varibles of date,snow, tmax and tmin in the five years from 2005 to 2010. We limit the snowfall amount to the range of 0mm to 100mm, and choose the coldest three months (November, December and January) as our targets. The first scatterplot we made is to explore the relationship between the minimum temperature and the maximum temperature based on the snowfall amounts. The second boxplot we made is to explore the snowfall distribution based on months in the selected five years. The third bar chart plot we made is to count the snowfall according to different years. 
   
For the shiny app, you can choose the year and month you are interested in, and the plots will change according to your choice.

###GitHub repo

Problem 1 [dashboard](https://github.com/EileenZh/p8105_hw6_hz2507)


Problem 2 [dashboard](https://github.com/zhaoyuliu/p8105_hw6_p2)

 
Problem 3 [website](https://github.com/EileenZh/p8105_hw6_p3)

